# Change these first
owner: hupratt # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Shop
    url: https://shop.lapetiteportugaise.eu
    __dangerous__disable_verify_peer: true
  - name: Posthog
    url: https://posthog.craftstudios.shop/setup_admin
    __dangerous__disable_verify_peer: true
  - name: Stream HLS encoding (slow)
    url: https://live.craftstudios.shop/
    __dangerous__disable_verify_peer: true
  - name: WebRTC encoding (fast)
    url: https://rtc.craftstudios.shop/
    __dangerous__disable_verify_peer: true
  - name: Portfolio
    url: https://portfolio.craftstudios.shop/
    __dangerous__disable_verify_peer: true
  - name: www
    url: https://www.craftstudios.shop/
    __dangerous__disable_verify_peer: true
  - name: Blog
    url: https://blog.craftstudios.shop/
    __dangerous__disable_verify_peer: true
  - name: Coach
    url: https://coach.craftstudios.shop/
    __dangerous__disable_verify_peer: true
  - name: Booking
    url: https://booking.craftstudios.shop/en/
    __dangerous__disable_verify_peer: true
  - name: Makita
    url: https://makita.craftstudios.shop/
    __dangerous__disable_verify_peer: true
  - name: Split a bill
    url: https://bill.craftstudios.shop/
    __dangerous__disable_verify_peer: true   
  - name: Mortgage Calculator
    url: https://mortgage-calculator-f1492f08-f236-4a55-afb7-70ded209cb25.s3.eu-west-2.amazonaws.com/serverless/index.html
    __dangerous__disable_verify_peer: true
  - name: CV
    url: https://rihab2-f1492f08-f236-4a55-afb7-70ded209cb24.s3.eu-west-2.amazonaws.com/index.html
    __dangerous__disable_verify_peer: true
  - name: netchicks
    url: https://netchicks-f1492f08-f236-4a55-afb7-70ded209cb24.s3.eu-west-2.amazonaws.com/index.html
    __dangerous__disable_verify_peer: true
  - name: youtubeclone
    url: https://youtube.craftstudios.shop/
    __dangerous__disable_verify_peer: true
  - name: bitwarden
    url: https://bitwarden.craftstudios.shop/
    __dangerous__disable_verify_peer: true
  - name: trello
    url: https://trello.craftstudios.shop/
    __dangerous__disable_verify_peer: true
  - name: retro
    url: https://retro.craftstudios.shop/
    __dangerous__disable_verify_peer: true
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://bookshop-images-f1492f08-f236-4a55-afb7-70ded209cb25.s3.eu-west-2.amazonaws.com/resources/craftstudios-logo.jpg
  name: Upptime
  theme: light
  introTitle: "HTTP Monitoring"
  introMessage: "**Upptime** is the HTTP monitoring tool powered entirely by GitHub actions."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
